# Generated by Django 5.0.6 on 2024-07-04 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(default='', max_length=500)),
                ('tags', models.CharField(default='', max_length=500)),
                ('duration', models.IntegerField(default=10)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('video', models.FileField(upload_to='video/pulse/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pulse', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_pulse', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='viewed_pulse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
