# Generated by Django 5.0.6 on 2024-07-04 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pulses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_pulses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='viewed_pulses', to=settings.AUTH_USER_MODEL),
        ),
    ]
