# Generated by Django 5.0.6 on 2024-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='beta_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
